module.exports = [
  { word: 'smile', chinese: '微笑', pinyin: 'wēi xiào', english: 'smile', phrase: '大家一起微笑', phraseEn: 'Everyone smiles together', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'happy', chinese: '高兴', pinyin: 'gāo xìng', english: 'happy', phrase: '我今天很高兴', phraseEn: 'I am very happy today', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'friend', chinese: '朋友', pinyin: 'péng yǒu', english: 'friend', phrase: '朋友一起玩耍', phraseEn: 'Friends play together', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'teacher', chinese: '老师', pinyin: 'lǎo shī', english: 'teacher', phrase: '老师在教室里', phraseEn: 'The teacher is in the classroom', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'student', chinese: '同学', pinyin: 'tóng xué', english: 'classmate', phrase: '同学互相帮助', phraseEn: 'Classmates help each other', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'morning', chinese: '早安', pinyin: 'zǎo ān', english: 'good morning', phrase: '见面先说早安', phraseEn: 'Say good morning when you meet', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'night', chinese: '晚安', pinyin: 'wǎn ān', english: 'good night', phrase: '睡前说晚安', phraseEn: 'Say good night before sleep', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'thanks', chinese: '谢谢', pinyin: 'xiè xie', english: 'thanks', phrase: '谢谢你的帮忙', phraseEn: 'Thanks for your help', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'sorry', chinese: '抱歉', pinyin: 'bào qiàn', english: 'sorry', phrase: '做错事要抱歉', phraseEn: 'Say sorry when you make mistakes', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'please', chinese: '请问', pinyin: 'qǐng wèn', english: 'excuse me', phrase: '请问老师问题', phraseEn: 'Ask the teacher politely', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },

  { word: 'clean', chinese: '干净', pinyin: 'gān jìng', english: 'clean', phrase: '地板很干净', phraseEn: 'The floor is clean', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'quiet', chinese: '安静', pinyin: 'ān jìng', english: 'quiet', phrase: '图书角要安静', phraseEn: 'Keep quiet in the reading corner', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'careful', chinese: '小心', pinyin: 'xiǎo xīn', english: 'careful', phrase: '走楼梯要小心', phraseEn: 'Be careful on the stairs', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'brave', chinese: '勇敢', pinyin: 'yǒng gǎn', english: 'brave', phrase: '你真的很勇敢', phraseEn: 'You are really brave', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'study', chinese: '学习', pinyin: 'xué xí', english: 'study', phrase: '我们认真学习', phraseEn: 'We study carefully', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'read', chinese: '看书', pinyin: 'kàn shū', english: 'read books', phrase: '午休前看书', phraseEn: 'Read books before nap time', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'draw', chinese: '画画', pinyin: 'huà huà', english: 'draw', phrase: '我喜欢画画', phraseEn: 'I like drawing', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'sing', chinese: '唱歌', pinyin: 'chàng gē', english: 'sing', phrase: '大家一起唱歌', phraseEn: 'Everyone sings together', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'dance', chinese: '跳舞', pinyin: 'tiào wǔ', english: 'dance', phrase: '音乐课要跳舞', phraseEn: 'Dance in music class', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'sunshine', chinese: '阳光', pinyin: 'yáng guāng', english: 'sunshine', phrase: '阳光照进窗户', phraseEn: 'Sunshine comes through the window', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },

  { word: 'rainbow', chinese: '彩虹', pinyin: 'cǎi hóng', english: 'rainbow', phrase: '雨后出现彩虹', phraseEn: 'A rainbow appears after rain', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'flower', chinese: '花朵', pinyin: 'huā duǒ', english: 'flower', phrase: '花朵开得很美', phraseEn: 'Flowers bloom beautifully', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'forest', chinese: '森林', pinyin: 'sēn lín', english: 'forest', phrase: '森林里有小鸟', phraseEn: 'There are birds in the forest', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'river', chinese: '小河', pinyin: 'xiǎo hé', english: 'river', phrase: '小河慢慢流动', phraseEn: 'The river flows slowly', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'cloud', chinese: '白云', pinyin: 'bái yún', english: 'cloud', phrase: '白云飘在天上', phraseEn: 'White clouds float in the sky', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'moon', chinese: '月亮', pinyin: 'yuè liàng', english: 'moon', phrase: '月亮挂在夜空', phraseEn: 'The moon hangs in the night sky', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'star', chinese: '星星', pinyin: 'xīng xing', english: 'star', phrase: '星星一闪一闪', phraseEn: 'Stars twinkle in the sky', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'spring', chinese: '春天', pinyin: 'chūn tiān', english: 'spring', phrase: '春天花儿开放', phraseEn: 'Flowers bloom in spring', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'winter', chinese: '冬天', pinyin: 'dōng tiān', english: 'winter', phrase: '冬天要穿外套', phraseEn: 'Wear a coat in winter', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'holiday', chinese: '节日', pinyin: 'jié rì', english: 'festival', phrase: '节日大家团聚', phraseEn: 'Families gather during festivals', difficulty: 'basic', stage: 'kindergarten', mode: 'bilingual' },

  { word: 'line_up', chinese: '排好队', pinyin: 'pái hǎo duì', english: 'line up', phrase: '小朋友排好队', phraseEn: 'Children line up nicely', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'wash_hands', chinese: '洗洗手', pinyin: 'xǐ xǐ shǒu', english: 'wash hands', phrase: '吃饭前洗洗手', phraseEn: 'Wash your hands before meals', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'drink_water', chinese: '多喝水', pinyin: 'duō hē shuǐ', english: 'drink water', phrase: '运动后多喝水', phraseEn: 'Drink more water after exercise', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'on_time', chinese: '要准时', pinyin: 'yào zhǔn shí', english: 'be on time', phrase: '上课一定要准时', phraseEn: 'Be on time for class', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'listen', chinese: '认真听', pinyin: 'rèn zhēn tīng', english: 'listen carefully', phrase: '上课认真听老师', phraseEn: 'Listen carefully to the teacher', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'speak_polite', chinese: '礼貌说', pinyin: 'lǐ mào shuō', english: 'speak politely', phrase: '请用礼貌说话', phraseEn: 'Please speak politely', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'share_toys', chinese: '分享玩具', pinyin: 'fēn xiǎng wán jù', english: 'share toys', phrase: '和朋友分享玩具', phraseEn: 'Share toys with friends', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'put_away', chinese: '收拾东西', pinyin: 'shōu shi dōng xi', english: 'put things away', phrase: '下课后收拾东西', phraseEn: 'Put things away after class', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'keep_tidy', chinese: '保持整洁', pinyin: 'bǎo chí zhěng jié', english: 'keep tidy', phrase: '教室要保持整洁', phraseEn: 'Keep the classroom tidy', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'cross_road', chinese: '安全过马路', pinyin: 'ān quán guò mǎ lù', english: 'cross safely', phrase: '牵好手过马路', phraseEn: 'Hold hands to cross the road', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },

  { word: 'finish_homework', chinese: '完成作业', pinyin: 'wán chéng zuò yè', english: 'finish homework', phrase: '回家先完成作业', phraseEn: 'Finish homework first at home', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'read_aloud', chinese: '大声朗读', pinyin: 'dà shēng lǎng dú', english: 'read aloud', phrase: '请大声朗读句子', phraseEn: 'Please read the sentence aloud', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'follow_rules', chinese: '遵守规则', pinyin: 'zūn shǒu guī zé', english: 'follow rules', phrase: '游戏时遵守规则', phraseEn: 'Follow the rules during games', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'wait_turn', chinese: '学会等待', pinyin: 'xué huì děng dài', english: 'learn to wait', phrase: '轮到别人要等待', phraseEn: 'Wait when it is someone else’s turn', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'say_thanks', chinese: '表达感谢', pinyin: 'biǎo dá gǎn xiè', english: 'express gratitude', phrase: '得到帮助表达感谢', phraseEn: 'Express thanks when helped', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'respect_teacher', chinese: '尊敬老师', pinyin: 'zūn jìng lǎo shī', english: 'respect teachers', phrase: '我们要尊敬老师', phraseEn: 'We should respect teachers', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'help_friend', chinese: '帮助朋友', pinyin: 'bāng zhù péng yǒu', english: 'help friends', phrase: '遇到困难帮助朋友', phraseEn: 'Help friends in trouble', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'protect_nature', chinese: '保护自然', pinyin: 'bǎo hù zì rán', english: 'protect nature', phrase: '我们一起保护自然', phraseEn: 'Let us protect nature together', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'love_family', chinese: '爱护家人', pinyin: 'ài hù jiā rén', english: 'care for family', phrase: '我们要爱护家人', phraseEn: 'We should care for family', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'good_habit', chinese: '养成习惯', pinyin: 'yǎng chéng xí guàn', english: 'build habits', phrase: '每天养成好习惯', phraseEn: 'Build good habits every day', difficulty: 'intermediate', stage: 'kindergarten', mode: 'bilingual' },

  { word: 'practice_perfect', chinese: '熟能生巧', pinyin: 'shú néng shēng qiǎo', english: 'practice makes perfect', phrase: '多练习就熟能生巧', phraseEn: 'Practice makes skills better', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'step_by_step', chinese: '循序渐进', pinyin: 'xún xù jiàn jìn', english: 'step by step', phrase: '学习要循序渐进', phraseEn: 'Learning should go step by step', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'focus', chinese: '专心致志', pinyin: 'zhuān xīn zhì zhì', english: 'be focused', phrase: '做事要专心致志', phraseEn: 'Stay focused when doing things', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'review_new', chinese: '温故知新', pinyin: 'wēn gù zhī xīn', english: 'review and learn new', phrase: '复习可以温故知新', phraseEn: 'Review helps you learn new things', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'unity_strength', chinese: '众志成城', pinyin: 'zhòng zhì chéng chéng', english: 'unity is strength', phrase: '团队合作众志成城', phraseEn: 'Teamwork shows united strength', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'be_honest', chinese: '诚实守信', pinyin: 'chéng shí shǒu xìn', english: 'honest and trustworthy', phrase: '做人要诚实守信', phraseEn: 'Be honest and trustworthy', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'diligent', chinese: '勤学好问', pinyin: 'qín xué hào wèn', english: 'study and ask', phrase: '孩子要勤学好问', phraseEn: 'Children should study and ask questions', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'think_first', chinese: '三思后行', pinyin: 'sān sī hòu xíng', english: 'think before acting', phrase: '做决定要三思后行', phraseEn: 'Think before making decisions', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'persevere', chinese: '持之以恒', pinyin: 'chí zhī yǐ héng', english: 'persevere', phrase: '学习需要持之以恒', phraseEn: 'Learning needs perseverance', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' },
  { word: 'strive_best', chinese: '精益求精', pinyin: 'jīng yì qiú jīng', english: 'strive for excellence', phrase: '做作品要精益求精', phraseEn: 'Keep improving your work', difficulty: 'advanced', stage: 'kindergarten', mode: 'bilingual' }
];
