// LEGO Basic Vocabulary - 极简版（使用 Twemoji CDN SVG 图标作为占位）
// 说明：采用通用表意 Emoji，避免版权与跨域问题。URL 示例：https://twemoji.maxcdn.com/v/latest/svg/1f9f1.svg

const LEGO_BASIC = [
];

// 导出（兼容浏览器与 Node）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = LEGO_BASIC;
} else if (typeof window !== 'undefined') {
  window.LEGO_BASIC = LEGO_BASIC;
}
  { word: "Brick", chinese: "乐高积木砖", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f1.svg"] },
  { word: "Minifigure", chinese: "小人仔", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9d1.svg"] },
  { word: "Car", chinese: "小汽车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f697.svg"] },
  { word: "Train", chinese: "火车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f686.svg"] },
  { word: "Boat", chinese: "小船", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26f5.svg"] },
  { word: "Airplane", chinese: "飞机", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2708.svg"] },
  { word: "Helicopter", chinese: "直升机", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f681.svg"] },
  { word: "Police Car", chinese: "警车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f693.svg"] },
  { word: "Fire Engine", chinese: "消防车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f692.svg"] },
  { word: "Ambulance", chinese: "救护车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f691.svg"] },
  { word: "House", chinese: "小房子", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3e0.svg"] },
  { word: "Door", chinese: "门", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6aa.svg"] },
  { word: "Window", chinese: "窗户", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa9f.svg"] },
  { word: "Wheel", chinese: "车轮", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6de.svg"] },
  { word: "Construction", chinese: "施工", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3d7.svg"] },
  { word: "Tree", chinese: "树", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f333.svg"] },
  { word: "Flower", chinese: "花", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f33c.svg"] },
  { word: "Dog", chinese: "小狗", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f436.svg"] },
  { word: "Cat", chinese: "小猫", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f431.svg"] },
  { word: "Bear", chinese: "小熊", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f43b.svg"] },
  { word: "Motorcycle", chinese: "摩托车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3cd.svg"] },
  // 大规模扩充（+50，达到100条）
  { word: "Elephant", chinese: "大象", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f418.svg"] },
  { word: "Giraffe", chinese: "长颈鹿", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f992.svg"] },
  { word: "Zebra", chinese: "斑马", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f993.svg"] },
  { word: "Monkey", chinese: "猴子", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f412.svg"] },
  { word: "Tiger", chinese: "老虎", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f405.svg"] },
  { word: "Bear", chinese: "熊", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f43b.svg"] },
  { word: "Penguin", chinese: "企鹅", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f427.svg"] },
  { word: "Owl", chinese: "猫头鹰", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f989.svg"] },
  { word: "Frog", chinese: "青蛙", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f438.svg"] },
  { word: "Turtle", chinese: "乌龟", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f422.svg"] },
  { word: "Butterfly", chinese: "蝴蝶", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f98b.svg"] },
  { word: "Bee", chinese: "蜜蜂", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41d.svg"] },
  { word: "Ladybug", chinese: "瓢虫", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41e.svg"] },
  { word: "Snail", chinese: "蜗牛", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f40c.svg"] },
  { word: "Octopus", chinese: "章鱼", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f419.svg"] },
  { word: "Whale", chinese: "鲸鱼", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f40b.svg"] },
  { word: "Dolphin", chinese: "海豚", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f42c.svg"] },
  { word: "Shark", chinese: "鲨鱼", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f988.svg"] },
  { word: "Crab", chinese: "螃蟹", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f980.svg"] },
  { word: "Starfish", chinese: "海星", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2b50.svg"] },
  { word: "Shell", chinese: "贝壳", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41a.svg"] },
  { word: "Sailboat", chinese: "帆船", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26f5.svg"] },
  { word: "Submarine", chinese: "潜水艇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6a4.svg"] },
  { word: "Truck", chinese: "卡车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f69a.svg"] },
  { word: "Fire Truck", chinese: "消防车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f692.svg"] },
  { word: "Police Car", chinese: "警车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f693.svg"] },
  { word: "Ambulance", chinese: "救护车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f691.svg"] },
  { word: "School Bus", chinese: "校车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f68c.svg"] },
  { word: "Taxi", chinese: "出租车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f695.svg"] },
  { word: "Scooter", chinese: "滑板车", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6f4.svg"] },
  { word: "Skateboard", chinese: "滑板", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6f9.svg"] },
  { word: "Roller Skates", chinese: "溜冰鞋", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6fc.svg"] },
  { word: "Swing", chinese: "秋千", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3a0.svg"] },
  { word: "Slide", chinese: "滑梯", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3a2.svg"] },
  { word: "Seesaw", chinese: "跷跷板", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2696.svg"] },
  { word: "Sandbox", chinese: "沙盒", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3d6.svg"] },
  { word: "Kite", chinese: "风筝", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa81.svg"] },
  { word: "Yo-yo", chinese: "悠悠球", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa80.svg"] },
  { word: "Top", chinese: "陀螺", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3af.svg"] },
  { word: "Puzzle", chinese: "拼图", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9e9.svg"] },
  { word: "Blocks", chinese: "积木", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f1.svg"] },
  { word: "Doll", chinese: "娃娃", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa86.svg"] },
  { word: "Teddy Bear", chinese: "泰迪熊", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f8.svg"] },
  { word: "Drum", chinese: "鼓", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f941.svg"] },
  { word: "Guitar", chinese: "吉他", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3b8.svg"] },
  { word: "Piano", chinese: "钢琴", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3b9.svg"] },
  { word: "Trumpet", chinese: "小号", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3ba.svg"] },
  { word: "Violin", chinese: "小提琴", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3bb.svg"] },
  { word: "Microphone", chinese: "麦克风", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3a4.svg"] },
  { word: "Camera", chinese: "相机", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4f7.svg"] },
  { word: "Television", chinese: "电视", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4fa.svg"] }