// Kirby Basic Vocabulary - 极简版（使用 Twemoji CDN SVG 图标作为占位）
// 说明：采用通用表意 Emoji，避免版权与跨域问题。URL 格式示例：https://twemoji.maxcdn.com/v/latest/svg/2b50.svg

const KIRBY_BASIC = [
];

// 导出（兼容浏览器与 Node）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = KIRBY_BASIC;
} else if (typeof window !== 'undefined') {
  window.KIRBY_BASIC = KIRBY_BASIC;
}
  { word: "Kirby", chinese: "卡比", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f497.svg"] },
  { word: "King Dedede", chinese: "帝帝帝大王", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f451.svg"] },
  { word: "Meta Knight", chinese: "魅塔骑士", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2694.svg"] },
  { word: "Waddle Dee", chinese: "瓦豆迪", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f424.svg"] },
  { word: "Warp Star", chinese: "飞行星星", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f320.svg"] },
  { word: "Maxim Tomato", chinese: "极限番茄", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f345.svg"] },
  { word: "Sword Ability", chinese: "剑能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f5e1.svg"] },
  { word: "Fire Ability", chinese: "火焰能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f525.svg"] },
  { word: "Ice Ability", chinese: "冰能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2744.svg"] },
  { word: "Hammer Ability", chinese: "锤子能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f528.svg"] },
  { word: "Parasol Ability", chinese: "雨伞能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2602.svg"] },
  { word: "Star Power", chinese: "星之力量", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2728.svg"] },
  { word: "Bandana Waddle Dee", chinese: "头巾瓦豆迪", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f94b.svg"] },
  { word: "Gooey", chinese: "古伊", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f5.svg"] },
  { word: "Magolor", chinese: "玛戈洛尔", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3f7.svg"] },
  { word: "Taranza", chinese: "塔兰萨", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f577.svg"] },
  { word: "Susie", chinese: "苏茜", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4bb.svg"] },
  { word: "Galacta Knight", chinese: "银河骑士", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2728.svg"] },
  { word: "Dark Meta Knight", chinese: "黑暗魅塔骑士", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f5a4.svg"] },
  { word: "Marx", chinese: "马克思", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f985.svg"] },
  { word: "Adeleine", chinese: "阿黛琳", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3a8.svg"] },
  { word: "Ribbon", chinese: "丝带妖精", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f380.svg"] },
  { word: "Elfilin", chinese: "艾菲琳", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f43f.svg"] },
  { word: "Fecto Forgo", chinese: "费克托·福尔戈", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f47e.svg"] },
  { word: "Nightmare", chinese: "梦魇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f319.svg"] },
  { word: "Daroach", chinese: "达洛奇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f400.svg"] },
  { word: "Chef Kawasaki", chinese: "川崎厨师", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f373.svg"] },
  { word: "Whispy Woods", chinese: "呼啦呼啦树/大树", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f333.svg"] },
  { word: "Kracko", chinese: "克拉科", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26c5.svg"] },
  { word: "Cutter Ability", chinese: "切割能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2702.svg"] },
  { word: "Beam Ability", chinese: "光束能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4a1.svg"] },
  { word: "Bomb Ability", chinese: "炸弹能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4a3.svg"] },
  { word: "Stone Ability", chinese: "石头能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26f0.svg"] },
  { word: "Wheel Ability", chinese: "车轮能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6de.svg"] },
  { word: "Wing Ability", chinese: "飞翼能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f985.svg"] },
  { word: "Jet Ability", chinese: "喷射能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f680.svg"] },
  { word: "Yo-Yo Ability", chinese: "悠悠球能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3ae.svg"] },
  { word: "Plasma Ability", chinese: "等离子能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26a1.svg"] },
  { word: "Mirror Ability", chinese: "镜子能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9ff.svg"] },
  { word: "Ninja Ability", chinese: "忍者能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f977.svg"] },
  { word: "Fighter Ability", chinese: "格斗能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f94a.svg"] },
  { word: "Suplex Ability", chinese: "背摔能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f94a.svg"] },
  { word: "Throw Ability", chinese: "投掷能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3b1.svg"] },
  { word: "Sleep Ability", chinese: "睡觉能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6cc.svg"] },
  { word: "Paint Ability", chinese: "绘画能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f58c.svg"] },
  { word: "Doctor Ability", chinese: "医生能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2695.svg"] },
  { word: "Poison Ability", chinese: "毒液能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2620.svg"] },
  { word: "Spider Ability", chinese: "蜘蛛能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f577.svg"] },
  { word: "ESP Ability", chinese: "超能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9e0.svg"] },
  { word: "Beetle Ability", chinese: "甲虫能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41e.svg"] },
  { word: "Bell Ability", chinese: "铃铛能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f514.svg"] },
  { word: "Circus Ability", chinese: "马戏能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3aa.svg"] },
  { word: "Archer Ability", chinese: "弓箭能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3f9.svg"] },
  { word: "Sand Ability", chinese: "沙子能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3dc.svg"] },
  { word: "Mecha Ability", chinese: "机甲能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f916.svg"] },
  { word: "Water Ability", chinese: "水流能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4a7.svg"] },
  { word: "Leaf Ability", chinese: "树叶能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f343.svg"] },
  { word: "Spear Ability", chinese: "长矛能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2694.svg"] },
  { word: "Whip Ability", chinese: "鞭子能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f6.svg"] },
  { word: "Snow Ability", chinese: "雪花能力", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2744.svg"] },
  { word: "Star Rod", chinese: "星之杖", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2728.svg"] },
  { word: "Invincible Candy", chinese: "无敌糖果", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f36c.svg"] },
  { word: "Food", chinese: "食物", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f35e.svg"] },
  { word: "Copy Essence", chinese: "复制之源", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f52e.svg"] },
  { word: "Halberd", chinese: "战舰哈尔伯德", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6f3.svg"] },
  { word: "Star Allies", chinese: "星之盟友", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2b50.svg"] },
  { word: "Dream Land", chinese: "梦幻之国", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3f0.svg"] }