// Super Mario Basic Vocabulary - 极简版（使用 Twemoji CDN SVG 图标作为占位）
// 说明：采用通用表意 Emoji，避免版权与跨域问题。URL 格式示例：https://twemoji.maxcdn.com/v/latest/svg/1f344.svg

const MARIO_BASIC = [
];

// 导出（兼容浏览器与 Node）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = MARIO_BASIC;
} else if (typeof window !== 'undefined') {
  window.MARIO_BASIC = MARIO_BASIC;
}
  { word: "Super Mushroom", chinese: "超级蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f344.svg"] },
  { word: "Fire Flower", chinese: "火焰花", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f525.svg"] },
  { word: "Super Star", chinese: "无敌星星", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2b50.svg"] },
  { word: "1-Up", chinese: "一命加一", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f340.svg"] },
  { word: "Question Block", chinese: "问号砖块", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2753.svg"] },
  { word: "Coin", chinese: "金币", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa99.svg"] },
  { word: "Goomba", chinese: "栗宝宝", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f330.svg"] },
  { word: "Koopa Troopa", chinese: "库巴兵", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f422.svg"] },
  { word: "Bowser", chinese: "库巴", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f409.svg"] },
  { word: "Yoshi", chinese: "耀西", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f995.svg"] },
  { word: "Princess Peach", chinese: "桃花公主", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f351.svg"] },
  { word: "Toad", chinese: "奇诺比奥", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f344.svg"] },
  { word: "Pipe", chinese: "水管", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6aa.svg"] },
  { word: "Flagpole", chinese: "终点旗杆", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f6a9.svg"] },
  { word: "Bullet Bill", chinese: "炮弹兵", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4a3.svg"] },
  { word: "Mario", chinese: "马里奥", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f534.svg"] },
  { word: "Luigi", chinese: "路易吉", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f7e2.svg"] },
  { word: "Princess Daisy", chinese: "黛西公主", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f478.svg"] },
  { word: "Rosalina", chinese: "罗莎琳娜", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2b50.svg"] },
  { word: "Bowser Jr.", chinese: "酷霸王Jr.", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f476.svg"] },
  { word: "Wario", chinese: "瓦里奥", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f7e1.svg"] },
  { word: "Waluigi", chinese: "瓦路易吉", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f7e3.svg"] },
  { word: "Kamek", chinese: "卡美克", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9d9.svg"] },
  { word: "Larry", chinese: "拉里", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9d1.svg"] },
  { word: "Morton", chinese: "莫顿", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26d4.svg"] },
  { word: "Wendy", chinese: "温蒂", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f48e.svg"] },
  { word: "Iggy", chinese: "伊奇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9e9.svg"] },
  { word: "Roy", chinese: "罗伊", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f60e.svg"] },
  { word: "Lemmy", chinese: "莱米", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3a3.svg"] },
  { word: "Ludwig", chinese: "路德维希", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f399.svg"] },
  { word: "Donkey Kong", chinese: "大金刚", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f98d.svg"] },
  { word: "Pauline", chinese: "波琳", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f3a4.svg"] },
  { word: "Birdo", chinese: "蛋头怪/啵波", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f95a.svg"] },
  { word: "Piranha Plant", chinese: "食人花", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f33f.svg"] },
  { word: "Boo", chinese: "布 Boo", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f47b.svg"] },
  { word: "Cheep Cheep", chinese: "刺鱼/赤鱼", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41f.svg"] },
  { word: "Blooper", chinese: "乌贼", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f991.svg"] },
  { word: "Hammer Bro", chinese: "铁锤兄弟", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f528.svg"] },
  { word: "Lakitu", chinese: "云中小子/拉奇库", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2601.svg"] },
  { word: "Shy Guy", chinese: "害羞幽灵", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f576.svg"] },
  { word: "Dry Bones", chinese: "骷髅龟", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f480.svg"] },
  { word: "Buzzy Beetle", chinese: "甲壳虫", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41e.svg"] },
  { word: "Spiny", chinese: "刺龟", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f1.svg"] },
  { word: "Monty Mole", chinese: "鼹鼠莫蒂", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f401.svg"] },
  { word: "Thwomp", chinese: "石头人/碾压石", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26f0.svg"] },
  { word: "Chain Chomp", chinese: "铁球咬咬", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26aa.svg"] },
  { word: "Magikoopa", chinese: "魔法库巴兵", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9d9.svg"] },
  { word: "Green Shell", chinese: "绿龟壳", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f422.svg"] },
  { word: "Red Shell", chinese: "红龟壳", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f422.svg"] },
  { word: "Ice Flower", chinese: "冰花", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2744.svg"] },
  { word: "Super Leaf", chinese: "超级树叶", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f343.svg"] },
  { word: "Tanooki Suit", chinese: "狸猫装", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f99d.svg"] },
  { word: "Cape Feather", chinese: "斗篷羽毛", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fab6.svg"] },
  { word: "Propeller Mushroom", chinese: "螺旋桨蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f32c.svg"] },
  { word: "Mini Mushroom", chinese: "迷你蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f344.svg"] },
  { word: "Mega Mushroom", chinese: "巨大蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f344.svg"] },
  { word: "Super Bell", chinese: "超级铃铛", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f514.svg"] },
  { word: "Super Acorn", chinese: "超级橡果", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f330.svg"] },
  { word: "Boomerang Flower", chinese: "回旋镖花", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa83.svg"] },
  { word: "Double Cherry", chinese: "双倍樱桃", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f352.svg"] },
  { word: "Cloud Flower", chinese: "云朵花", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2601.svg"] },
  { word: "Rock Mushroom", chinese: "岩石蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/26f0.svg"] },
  { word: "Cape", chinese: "披风", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9e3.svg"] },
  { word: "Star Coin", chinese: "星币", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/2b50.svg"] },
  { word: "Fire Mario", chinese: "火焰马里奥", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f525.svg"] },
  { word: "Cat Mario", chinese: "猫猫马里奥", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f431.svg"] },
  { word: "Tanooki Mario", chinese: "狸猫马里奥", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f99d.svg"] },
  { word: "Bee Mushroom", chinese: "蜜蜂蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f41d.svg"] },
  { word: "Spring Mushroom", chinese: "弹簧蘑菇", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f9f5.svg"] },
  { word: "Penguin Suit", chinese: "企鹅装", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f427.svg"] },
  { word: "Boomerang Bro", chinese: "回旋镖兄弟", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1fa83.svg"] },
  { word: "Koopa Clown Car", chinese: "小丑飞船", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f680.svg"] },
  { word: "Super Horn", chinese: "超级喇叭", imageURLs: ["https://twemoji.maxcdn.com/v/latest/svg/1f4e2.svg"] }