#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const { DatabaseSync } = require("node:sqlite");

const ROOT = process.cwd();
const DB_PATH = path.join(ROOT, "data", "vocab.db");
const OUT_DIR = path.join(ROOT, "js", "vocabularies", "normalized");
const OUT_FILE = path.join(OUT_DIR, "core_from_db.js");

function main() {
  if (!fs.existsSync(DB_PATH)) {
    throw new Error("Missing data/vocab.db. Run npm run vocabdb:init first.");
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const db = new DatabaseSync(DB_PATH);

  const entries = db
    .prepare(
      `SELECT id, lemma_key, word, standardized, chinese, phonetic, phrase, phrase_translation, difficulty, category, status
       FROM entries
       WHERE status='active'
       ORDER BY lemma_key`
    )
    .all();

  const imgStmt = db.prepare(
    `SELECT filename, url, type
     FROM entry_images
     WHERE entry_id=?
     ORDER BY is_primary DESC, id ASC`
  );

  const srcStmt = db.prepare(
    `SELECT source_file, source_group, source_version
     FROM entry_sources
     WHERE entry_id=?
     ORDER BY id ASC`
  );

  const out = [];
  for (const e of entries) {
    const images = imgStmt.all(e.id).map((x) => ({
      filename: x.filename || "auto.jpg",
      url: x.url || "",
      type: x.type || "Concept Image",
    }));
    const sources = srcStmt.all(e.id);

    out.push({
      word: e.word || e.standardized || e.lemma_key,
      standardized: e.standardized || e.word || e.lemma_key,
      chinese: e.chinese || "",
      phonetic: e.phonetic || "",
      phrase: e.phrase || "",
      phraseTranslation: e.phrase_translation || "",
      difficulty: e.difficulty || "",
      category: e.category || "",
      imageURLs: images,
      sources: sources,
    });
  }

  const banner = [
    "// Auto-generated from data/vocab.db by scripts/vocab_db/export_vocab_db_js.js",
    "// Do not edit this file manually.",
  ].join("\n");
  const content = `${banner}\nconst CORE_FROM_DB = ${JSON.stringify(out, null, 2)};\n`;
  fs.writeFileSync(OUT_FILE, content, "utf8");

  const summary = {
    generatedAt: new Date().toISOString(),
    database: path.relative(ROOT, DB_PATH),
    output: path.relative(ROOT, OUT_FILE),
    entries: out.length,
  };
  console.log(JSON.stringify(summary, null, 2));
}

main();

