name: Windows EXE (Online via Nativefier)

on:
  workflow_dispatch:
    inputs:
      app_url:
        description: 'Online URL to wrap (must be publicly accessible)'
        required: true
        type: string
      app_name:
        description: 'App name for EXE'
        required: false
        default: 'MinecraftWords'
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Windows EXE with Nativefier
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $APP_URL = '${{ inputs.app_url }}'
          $APP_NAME = '${{ inputs.app_name }}'
          if (-not $APP_URL) { throw 'app_url is required' }
          npx nativefier --name "$APP_NAME" --platform windows --arch x64 --disable-dev-tools --single-instance "$APP_URL"
          # 打包逻辑移动到独立步骤，避免路径不一致

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-${{ github.run_id }}
          path: "*.zip"